### ISSUE TITLE
Unproccesed Youtube transcripts.

### ISSUE THREAD

**Issue by waabiMkwa** [noncoding3torus/ReferenceMaterial#1]
Hey man,

High Strangeness subreddit lurker here, saw your post. 

I also saw that you wished you had transcripts for the videos...

I tried to get as many as I could. There's 46 of them here. None have been vetted for accuracy, but it's something.

**Comment by waabiMkwa** [comment]
let me know if you would prefer them as single blocks of text format with no timestamps.

**Comment by noncoding3torus** [comment]
HOLY SMOKES!  THANK YOU!  I will take a look at them!  That is awesome!  How do you get these?  Is there a youtube API?  Rip them out of the stream?

**Comment by noncoding3torus** [comment]
I now see you can copy them right out of youtube.  Thank you!  I will get them in here!  You are awesome!

**Comment by waabiMkwa** [comment]
Yeah I'm using a couple APIs. I also threw together a few summaries for about 20 of them.

**Comment by waabiMkwa** [comment]
[summaries.zip](https://github.com/noncoding3torus/ReferenceMaterial/files/8189925/summaries.zip)

**Comment by waabiMkwa** [comment]
Again, they are summarized with the unprocessed text, so there will be accuracy problems. But they can help a little bit I think.
